package homeworkSah;

/**
 * Created by crtanasescu on 1/17/2017.
 */
public enum DirectieRegina {
    INAINTE, INAPOI, STANGA, DREAPTA, INAINTE_SI_STANGA_PE_DIAGONALA, INAINTE_SI_DREAPTA_PE_DIAGONALA, INAPOI_SI_STANGA_PE_DIAGONALA, INAPOI_SI_DREAPTA_PE_DIAGONALA
}
